language: node_js

# This is to make the build not fail when there are no tests  
# It is possible that this simply skips tests all together though
script: 'true'

node_js:
  - 12.19.0

script:
  - CI=true npm test --passWithNoTests
  - npm run build

notifications:
  email:
    - rlreamy@umich.edu
    - zwright@umich.edu
